language: node_js
node_js:
  - '8'
after_success:
  - yarn lint || echo "Let's show the lint output here but we don't want it cause a failure yet"
  - yarn report-coverage
deploy:
  provider: npm
  email: peter@terascope.io
  api_key:
    secure: "kywjw2Q+iaV+PlgtOu4yVAlNpRnIwTKa807XYgPD1raVlZYGa2fC0rn5NMD1Gm5HD45Blea5aBhBXIp8+wn1/qTXh/8udkWRViV4AivI0k8duJBTucIZVi8LGADzfP23pHo9uvBhi2dun+RWbljowbi0MWPWa2sylbCV9VHjXdJIk3J43eMTmVvzjvtlN4HCzBXWL2l6dbD4GeGLya7OYRw3Wr2qG4WzARBIVy5kAIkFqW5AoBkx3m2HcFlTikO5RlzX3LGpzi5ryt31G+CgZt67ZF7B2ugXaW3SWfyXmXFINITxRbv7BFxjjGIjYZF1hzvEDPSF9PwjcAok/BtIKJH4B3mqm/zrI1UfwQvL+QHJt0vakKbalJf7RwH68Sh/MfUARTkCDHHLrcbVlh5CwlydDRnvTjxUensKvbY0VMk8gCllfW3NvPeaIE+cstpanC9GoZwWnhV/GIml4snVPbRnGuopNfZz3eHDC+8JscldNWid2yjuolNRWEpRDTtTfYa02Ac5B+Yr4rfBb9k/U+SUAA9DAXIllPRoxPyKhg8wqKpccdtQm4ggNMmlWFPwJZl3XvNILN0iVVRvjjJym64VAlwgPAkAxklca31pDdYwaSDHC7FEA5rx4eAdblQY4l+Xxc391dOqTVbFY/xbJohN/QiKt72w3WJdLrG7yQ8="
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
    branch: master
    repo: terascope/queue
